const FORUM_ICON_MAP: Record<string, string> = {
	'off-topic': 'fid-6',
	feda: 'fid-90',
	ofertas: 'fid-149',
	streamers: 'fid-165',
	criptomonedas: 'fid-156',
	'compra-venta': 'fid-112',
	'estudios-trabajo': 'fid-132',
	ciencia: 'fid-148',
	musica: 'fid-23',
	cine: 'fid-102',
	tv: 'fid-82',
	'libros-comics': 'fid-109',
	'anime-manga': 'fid-99',
	deportes: 'fid-32',
	motor: 'fid-96',
	cocina: 'fid-127',
	fitness: 'fid-116',
	mascotas: 'fid-126',
	viajes: 'fid-106',
	shopping: 'fid-113',
	juegos: 'fid-7',
	'juegos-comunidad': 'fid-52',
	mmo: 'fid-26',
	'juegos-lucha': 'fid-150',
	'juegos-movil': 'fid-136',
	'juegos-mesa-rol': 'fid-133',
	mafia: 'fid-164',
	'club-hucha': 'fid-135',
	intercambios: 'fid-144',
	counterstrike: 'fid-1',
	diablo: 'fid-114',
	ffxiv: 'fid-147',
	lol: 'fid-110',
	lostark: 'fid-166',
	poe: 'fid-137',
	pokemon: 'fid-128',
	valorant: 'fid-162',
	wow: 'fid-38',
	dev: 'fid-9',
	gamedev: 'fid-143',
	'electronica-telefonia': 'fid-83',
	'hard-soft': 'fid-3',
	mediavida: 'fid-4',
	// politica shares the same icon as feda on Mediavida
	politica: 'fid-90',
}

export function getIconClassBySlug(slug: string): string {
	return FORUM_ICON_MAP[slug] ?? 'fid-desconocido'
}
