/**
 * Subforum Categories
 * Generated from Mediavida's nuevo-hilo pages
 *
 * Each subforum has its own set of categories (tags)
 * Format: { value: string, label: string }
 */

export interface SubforumCategory {
	value: string
	label: string
}

export type SubforumCategories = Record<string, SubforumCategory[]>

export const SUBFORUM_CATEGORIES: SubforumCategories = {
	// ─── GENERAL ───

	'off-topic': [
		{ value: '54', label: 'Amor' },
		{ value: '13', label: 'Clásico' },
		{ value: '142', label: 'Compras' },
		{ value: '156', label: 'Debate' },
		{ value: '2', label: 'Evento' },
		{ value: '7', label: 'Gracioso' },
		{ value: '181', label: 'Miscelánea' },
		{ value: '1', label: 'Noticia' },
		{ value: '52', label: 'Política' },
		{ value: '14', label: 'Pregunta' },
		{ value: '4', label: 'Queja' },
		{ value: '241', label: 'Rusos' },
		{ value: '16', label: 'Sexo' },
		{ value: '110', label: 'Viajes' },
		{ value: '132', label: 'Vídeos' },
	],

	feda: [
		{ value: '94', label: 'Curioso' },
		{ value: '5', label: 'Estúpido' },
		{ value: '7', label: 'Gracioso' },
		{ value: '91', label: 'Imágenes' },
		{ value: '9', label: 'Juegos' },
		{ value: '92', label: 'Me rayo' },
		{ value: '1', label: 'Noticia' },
		{ value: '14', label: 'Pregunta' },
		{ value: '4', label: 'Queja' },
		{ value: '16', label: 'Sexo' },
	],

	'club-hucha': [
		{ value: '397', label: 'Alimentación' },
		{ value: '172', label: 'Android' },
		{ value: '142', label: 'Compras' },
		{ value: '2', label: 'Evento' },
		{ value: '333', label: 'Físico' },
		{ value: '88', label: 'Gadgets' },
		{ value: '78', label: 'Hardware' },
		{ value: '396', label: 'Hogar' },
		{ value: '174', label: 'iOS' },
		{ value: '331', label: 'Móviles' },
		{ value: '347', label: 'Nintendo Switch' },
		{ value: '176', label: 'Off Topic' },
		{ value: '204', label: 'Otros' },
		{ value: '289', label: 'PlayStation 4' },
		{ value: '14', label: 'Pregunta' },
		{ value: '205', label: 'Ropa' },
		{ value: '344', label: 'Software' },
		{ value: '110', label: 'Viajes' },
		{ value: '81', label: 'Windows' },
		{ value: '298', label: 'Xbox One' },
	],

	politica: [
		{ value: '391', label: 'Famosos' },
		{ value: '388', label: 'Internacional' },
		{ value: '389', label: 'Memes' },
		{ value: '387', label: 'Nacional' },
		{ value: '390', label: 'Teoría Política' },
	],

	streamers: [
		{ value: '372', label: 'Clip' },
		{ value: '2', label: 'Evento' },
		{ value: '170', label: 'Guía' },
		{ value: '373', label: 'Salsa' },
		{ value: '139', label: 'Soporte Técnico' },
		{ value: '242', label: 'Stream' },
	],

	criptomonedas: [
		{ value: '355', label: 'Altcoin' },
		{ value: '353', label: 'Banco' },
		{ value: '356', label: 'Bitcoin' },
		{ value: '352', label: 'Bolsa' },
		{ value: '156', label: 'Debate' },
		{ value: '170', label: 'Guía' },
		{ value: '354', label: 'Humor' },
		{ value: '350', label: 'ICO' },
		{ value: '351', label: 'Minado' },
		{ value: '1', label: 'Noticia' },
	],

	'compra-venta': [
		{ value: '88', label: 'Gadgets' },
		{ value: '78', label: 'Hardware' },
		{ value: '9', label: 'Juegos' },
		{ value: '204', label: 'Otros' },
		{ value: '205', label: 'Ropa' },
	],

	'estudios-trabajo': [
		{ value: '270', label: 'Ciencias' },
		{ value: '310', label: 'Curso' },
		{ value: '262', label: 'Formación Profesional' },
		{ value: '271', label: 'Idiomas' },
		{ value: '272', label: 'Instituto' },
		{ value: '273', label: 'Letras' },
		{ value: '274', label: 'Oposiciones' },
		{ value: '204', label: 'Otros' },
		{ value: '14', label: 'Pregunta' },
		{ value: '275', label: 'Trabajo' },
	],

	ciencia: [
		{ value: '339', label: 'Astronomía' },
		{ value: '337', label: 'Biología' },
		{ value: '8', label: 'Ciencia' },
		{ value: '340', label: 'Ciencias Sociales' },
		{ value: '156', label: 'Debate' },
		{ value: '2', label: 'Evento' },
		{ value: '341', label: 'Física' },
		{ value: '336', label: 'Matemáticas' },
		{ value: '1', label: 'Noticia' },
		{ value: '338', label: 'Química' },
		{ value: '342', label: 'Salud' },
	],

	musica: [
		{ value: '318', label: 'Ambient' },
		{ value: '317', label: 'Americana' },
		{ value: '156', label: 'Debate' },
		{ value: '109', label: 'Electrónica' },
		{ value: '2', label: 'Evento' },
		{ value: '62', label: 'Metal' },
		{ value: '1', label: 'Noticia' },
		{ value: '147', label: 'Otros' },
		{ value: '63', label: 'Pop' },
		{ value: '14', label: 'Pregunta' },
		{ value: '319', label: 'Punk' },
		{ value: '64', label: 'Rap' },
		{ value: '61', label: 'Rock' },
	],

	cine: [
		{ value: '39', label: 'Acción' },
		{ value: '43', label: 'Animación' },
		{ value: '155', label: 'Aventuras' },
		{ value: '41', label: 'Ciencia ficción' },
		{ value: '15', label: 'Cine' },
		{ value: '40', label: 'Comedia' },
		{ value: '156', label: 'Debate' },
		{ value: '38', label: 'Documental' },
		{ value: '42', label: 'Drama' },
		{ value: '303', label: 'Fantasía' },
		{ value: '198', label: 'Historia' },
		{ value: '1', label: 'Noticia' },
		{ value: '14', label: 'Pregunta' },
		{ value: '44', label: 'Terror' },
		{ value: '154', label: 'Thriller' },
	],

	tv: [
		{ value: '39', label: 'Acción' },
		{ value: '43', label: 'Animación' },
		{ value: '155', label: 'Aventuras' },
		{ value: '41', label: 'Ciencia ficción' },
		{ value: '40', label: 'Comedia' },
		{ value: '156', label: 'Debate' },
		{ value: '38', label: 'Documental' },
		{ value: '42', label: 'Drama' },
		{ value: '313', label: 'HBO' },
		{ value: '304', label: 'Misterio' },
		{ value: '1', label: 'Noticia' },
		{ value: '14', label: 'Pregunta' },
		{ value: '75', label: 'Reality show' },
		{ value: '44', label: 'Terror' },
		{ value: '154', label: 'Thriller' },
		{ value: '18', label: 'TV' },
	],

	'libros-comics': [
		{ value: '155', label: 'Aventuras' },
		{ value: '41', label: 'Ciencia ficción' },
		{ value: '13', label: 'Clásico' },
		{ value: '66', label: 'Cómic' },
		{ value: '156', label: 'Debate' },
		{ value: '42', label: 'Drama' },
		{ value: '303', label: 'Fantasía' },
		{ value: '199', label: 'Ficción' },
		{ value: '243', label: 'Grupo de lectura' },
		{ value: '198', label: 'Historia' },
		{ value: '181', label: 'Miscelánea' },
		{ value: '304', label: 'Misterio' },
		{ value: '200', label: 'No ficción' },
		{ value: '1', label: 'Noticia' },
		{ value: '201', label: 'Poesía' },
		{ value: '14', label: 'Pregunta' },
		{ value: '44', label: 'Terror' },
	],

	'anime-manga': [
		{ value: '29', label: 'Anime' },
		{ value: '156', label: 'Debate' },
		{ value: '2', label: 'Evento' },
		{ value: '9', label: 'Juegos' },
		{ value: '321', label: 'Light Novel' },
		{ value: '30', label: 'Manga' },
		{ value: '1', label: 'Noticia' },
		{ value: '179', label: 'Otaku' },
		{ value: '320', label: 'OVA' },
		{ value: '180', label: 'Películas' },
		{ value: '14', label: 'Pregunta' },
		{ value: '4', label: 'Queja' },
		{ value: '132', label: 'Vídeos' },
	],

	deportes: [
		{ value: '314', label: 'Apuestas' },
		{ value: '48', label: 'Baloncesto' },
		{ value: '156', label: 'Debate' },
		{ value: '10', label: 'Deportes' },
		{ value: '49', label: 'Fitness' },
		{ value: '46', label: 'Fútbol' },
		{ value: '47', label: 'Fútbol internacional' },
		{ value: '7', label: 'Gracioso' },
		{ value: '50', label: 'Lucha' },
		{ value: '135', label: 'Mercado' },
		{ value: '1', label: 'Noticia' },
		{ value: '204', label: 'Otros' },
		{ value: '14', label: 'Pregunta' },
		{ value: '51', label: 'Tenis' },
	],

	motor: [
		{ value: '142', label: 'Compras' },
		{ value: '156', label: 'Debate' },
		{ value: '55', label: 'Formula 1' },
		{ value: '7', label: 'Gracioso' },
		{ value: '57', label: 'Mecánica' },
		{ value: '143', label: 'Monoplazas' },
		{ value: '56', label: 'Motocicletas' },
		{ value: '285', label: 'MotoGP' },
		{ value: '160', label: 'Motor' },
		{ value: '1', label: 'Noticia' },
		{ value: '14', label: 'Pregunta' },
		{ value: '58', label: 'Pruebas' },
		{ value: '59', label: 'Rallies' },
		{ value: '60', label: 'Tuning' },
		{ value: '141', label: 'Turismos' },
	],

	cocina: [
		{ value: '254', label: 'Bebida' },
		{ value: '251', label: 'Carne' },
		{ value: '197', label: 'Comunidad' },
		{ value: '253', label: 'Dulces' },
		{ value: '258', label: 'Menaje' },
		{ value: '1', label: 'Noticia' },
		{ value: '257', label: 'Otros' },
		{ value: '256', label: 'Pan y pizza' },
		{ value: '252', label: 'Pescado y marisco' },
		{ value: '255', label: 'Vegetal' },
		{ value: '132', label: 'Vídeos' },
	],

	fitness: [
		{ value: '10', label: 'Deportes' },
		{ value: '233', label: 'Diarios' },
		{ value: '213', label: 'General' },
		{ value: '212', label: 'Lesiones' },
		{ value: '210', label: 'Musculación' },
		{ value: '209', label: 'Nutrición' },
	],

	mascotas: [
		{ value: '246', label: 'Acuarios' },
		{ value: '250', label: 'Artrópodos' },
		{ value: '248', label: 'Aves' },
		{ value: '197', label: 'Comunidad' },
		{ value: '245', label: 'Gatos' },
		{ value: '249', label: 'Mamíferos' },
		{ value: '1', label: 'Noticia' },
		{ value: '244', label: 'Perros' },
		{ value: '247', label: 'Reptiles' },
	],

	viajes: [
		{ value: '166', label: 'África' },
		{ value: '169', label: 'América' },
		{ value: '167', label: 'Asia' },
		{ value: '38', label: 'Documental' },
		{ value: '164', label: 'España' },
		{ value: '165', label: 'Europa' },
		{ value: '7', label: 'Gracioso' },
		{ value: '181', label: 'Miscelánea' },
		{ value: '1', label: 'Noticia' },
		{ value: '168', label: 'Oceanía' },
		{ value: '14', label: 'Pregunta' },
	],

	// ─── JUEGOS ───

	juegos: [
		{ value: '156', label: 'Debate' },
		{ value: '369', label: 'Hilo general' },
		{ value: '22', label: 'Multiplataforma' },
		{ value: '392', label: 'Nintendo' },
		{ value: '1', label: 'Noticia' },
		{ value: '395', label: 'Otras' },
		{ value: '26', label: 'PC' },
		{ value: '394', label: 'PlayStation' },
		{ value: '368', label: 'PlayStation 5' },
		{ value: '27', label: 'Retro' },
		{ value: '242', label: 'Stream' },
		{ value: '370', label: 'Tráiler' },
		{ value: '393', label: 'Xbox' },
		{ value: '367', label: 'Xbox Series X' },
	],

	mmo: [
		{ value: '77', label: 'Free to play' },
		{ value: '28', label: 'Juego web' },
		{ value: '22', label: 'Multiplataforma' },
		{ value: '24', label: 'Nintendo DS' },
		{ value: '1', label: 'Noticia' },
		{ value: '176', label: 'Off Topic' },
		{ value: '26', label: 'PC' },
		{ value: '175', label: 'PC Consolas' },
		{ value: '20', label: 'PlayStation 3' },
		{ value: '289', label: 'PlayStation 4' },
		{ value: '14', label: 'Pregunta' },
		{ value: '23', label: 'Wii' },
		{ value: '21', label: 'Xbox 360' },
	],

	'juegos-lucha': [
		{ value: '156', label: 'Debate' },
		{ value: '170', label: 'Guía' },
		{ value: '50', label: 'Lucha' },
		{ value: '1', label: 'Noticia' },
		{ value: '137', label: 'Periféricos' },
		{ value: '14', label: 'Pregunta' },
		{ value: '27', label: 'Retro' },
		{ value: '121', label: 'Torneo' },
		{ value: '132', label: 'Vídeos' },
	],

	'juegos-mesa-rol': [
		{ value: '263', label: 'Cartas' },
		{ value: '264', label: 'De mesa' },
		{ value: '265', label: 'Partida' },
		{ value: '14', label: 'Pregunta' },
		{ value: '266', label: 'Rol' },
		{ value: '267', label: 'Taller' },
		{ value: '268', label: 'Wargames' },
	],

	mafia: [
		{ value: '376', label: 'Avanzada' },
		{ value: '377', label: 'Bastarda' },
		{ value: '156', label: 'Debate' },
		{ value: '375', label: 'Estándar' },
		{ value: '378', label: 'Experimental' },
		{ value: '380', label: 'GMs' },
		{ value: '371', label: 'Inscripciones' },
		{ value: '379', label: 'Novatos' },
		{ value: '265', label: 'Partida' },
		{ value: '381', label: 'Players' },
		{ value: '374', label: 'Postpartida' },
		{ value: '14', label: 'Pregunta' },
		{ value: '178', label: 'Recursos' },
	],

	counterstrike: [
		{ value: '314', label: 'Apuestas' },
		{ value: '108', label: 'Config' },
		{ value: '283', label: 'Counter-Strike 1.6' },
		{ value: '284', label: 'Counter-Strike: Source' },
		{ value: '343', label: 'Equipos' },
		{ value: '135', label: 'Mercado' },
		{ value: '1', label: 'Noticia' },
		{ value: '176', label: 'Off Topic' },
		{ value: '14', label: 'Pregunta' },
		{ value: '4', label: 'Queja' },
		{ value: '121', label: 'Torneo' },
		{ value: '132', label: 'Vídeos' },
	],

	diablo: [
		{ value: '385', label: 'Bárbaro' },
		{ value: '282', label: 'Comercio' },
		{ value: '197', label: 'Comunidad' },
		{ value: '232', label: 'Diablo II' },
		{ value: '386', label: 'Diablo III' },
		{ value: '186', label: 'Druida' },
		{ value: '170', label: 'Guía' },
		{ value: '384', label: 'Hechicera' },
		{ value: '382', label: 'Nigromante' },
		{ value: '1', label: 'Noticia' },
		{ value: '176', label: 'Off Topic' },
		{ value: '383', label: 'Pícara' },
		{ value: '14', label: 'Pregunta' },
		{ value: '4', label: 'Queja' },
		{ value: '242', label: 'Stream' },
		{ value: '121', label: 'Torneo' },
		{ value: '132', label: 'Vídeos' },
	],

	lol: [
		{ value: '197', label: 'Comunidad' },
		{ value: '214', label: 'Dominion' },
		{ value: '170', label: 'Guía' },
		{ value: '1', label: 'Noticia' },
		{ value: '176', label: 'Off Topic' },
		{ value: '117', label: 'Parche' },
		{ value: '335', label: 'PBE' },
		{ value: '14', label: 'Pregunta' },
		{ value: '4', label: 'Queja' },
		{ value: '121', label: 'Torneo' },
		{ value: '334', label: 'Traspasos' },
		{ value: '132', label: 'Vídeos' },
	],

	poe: [
		{ value: '349', label: 'Articulo' },
		{ value: '282', label: 'Comercio' },
		{ value: '197', label: 'Comunidad' },
		{ value: '2', label: 'Evento' },
		{ value: '170', label: 'Guía' },
		{ value: '1', label: 'Noticia' },
		{ value: '176', label: 'Off Topic' },
		{ value: '14', label: 'Pregunta' },
		{ value: '242', label: 'Stream' },
		{ value: '132', label: 'Vídeos' },
	],

	pokemon: [
		{ value: '29', label: 'Anime' },
		{ value: '261', label: 'Clásicos' },
		{ value: '197', label: 'Comunidad' },
		{ value: '86', label: 'Galería' },
		{ value: '170', label: 'Guía' },
		{ value: '181', label: 'Miscelánea' },
		{ value: '1', label: 'Noticia' },
		{ value: '260', label: 'Online' },
		{ value: '365', label: 'Pokémon Espada/Escudo' },
		{ value: '345', label: 'Pokémon GO' },
		{ value: '364', label: "Pokémon Let's Go!" },
		{ value: '348', label: 'Pokémon Sol/Luna' },
		{ value: '14', label: 'Pregunta' },
		{ value: '121', label: 'Torneo' },
		{ value: '132', label: 'Vídeos' },
	],

	valorant: [
		{ value: '197', label: 'Comunidad' },
		{ value: '156', label: 'Debate' },
		{ value: '1', label: 'Noticia' },
		{ value: '14', label: 'Pregunta' },
		{ value: '4', label: 'Queja' },
		{ value: '139', label: 'Soporte Técnico' },
		{ value: '121', label: 'Torneo' },
		{ value: '132', label: 'Vídeos' },
	],

	wow: [
		{ value: '183', label: 'Brujo' },
		{ value: '184', label: 'Caballero de la Muerte' },
		{ value: '185', label: 'Cazador' },
		{ value: '346', label: 'Cazador de demonios' },
		{ value: '182', label: 'Chamán' },
		{ value: '186', label: 'Druida' },
		{ value: '187', label: 'Guerrero' },
		{ value: '188', label: 'Mago' },
		{ value: '269', label: 'Monje' },
		{ value: '1', label: 'Noticia' },
		{ value: '176', label: 'Off Topic' },
		{ value: '189', label: 'Paladín' },
		{ value: '190', label: 'Pícaro' },
		{ value: '14', label: 'Pregunta' },
		{ value: '119', label: 'PvE' },
		{ value: '118', label: 'PvP' },
		{ value: '191', label: 'Sacerdote' },
	],

	'juegos-movil': [
		{ value: '172', label: 'Android' },
		{ value: '174', label: 'iOS' },
		{ value: '22', label: 'Multiplataforma' },
		{ value: '1', label: 'Noticia' },
		{ value: '173', label: 'Windows Phone' },
	],

	intercambios: [
		{ value: '170', label: 'Guía' },
		{ value: '278', label: 'Intercambio' },
		{ value: '181', label: 'Miscelánea' },
		{ value: '1', label: 'Noticia' },
		{ value: '14', label: 'Pregunta' },
		{ value: '311', label: 'Tienda' },
		{ value: '312', label: 'Vendo' },
	],

	// ─── TECNOLOGÍA ───

	dev: [
		{ value: '84', label: 'Código' },
		{ value: '297', label: 'Desarrollo de juegos' },
		{ value: '300', label: 'Desarrollo móvil' },
		{ value: '299', label: 'Desarrollo web' },
		{ value: '85', label: 'Diseño' },
		{ value: '177', label: 'Fotografía' },
		{ value: '86', label: 'Galería' },
		{ value: '301', label: 'Se busca' },
	],

	ia: [
		{ value: '89', label: 'Audio' },
		{ value: '84', label: 'Código' },
		{ value: '408', label: 'Creaciones' },
		{ value: '407', label: 'Imagen' },
		{ value: '406', label: 'Modelos' },
		{ value: '409', label: 'Otros' },
		{ value: '90', label: 'Vídeo' },
	],

	gamedev: [
		{ value: '306', label: '2D' },
		{ value: '307', label: '3D' },
		{ value: '89', label: 'Audio' },
		{ value: '84', label: 'Código' },
		{ value: '310', label: 'Curso' },
		{ value: '2', label: 'Evento' },
		{ value: '86', label: 'Galería' },
		{ value: '170', label: 'Guía' },
		{ value: '309', label: 'Jugabilidad' },
		{ value: '87', label: 'Móviles' },
		{ value: '1', label: 'Noticia' },
		{ value: '176', label: 'Off Topic' },
		{ value: '14', label: 'Pregunta' },
		{ value: '178', label: 'Recursos' },
		{ value: '301', label: 'Se busca' },
		{ value: '308', label: 'Work in progress' },
	],

	'electronica-telefonia': [
		{ value: '302', label: 'Accesorios' },
		{ value: '172', label: 'Android' },
		{ value: '208', label: 'BlackBerry' },
		{ value: '2', label: 'Evento' },
		{ value: '174', label: 'iOS' },
		{ value: '87', label: 'Móviles' },
		{ value: '1', label: 'Noticia' },
		{ value: '288', label: 'Operadoras' },
		{ value: '287', label: 'Tabletas' },
		{ value: '18', label: 'TV' },
		{ value: '173', label: 'Windows Phone' },
	],

	'hard-soft': [
		{ value: '83', label: '*nix' },
		{ value: '78', label: 'Hardware' },
		{ value: '82', label: 'Mac' },
		{ value: '362', label: 'Monitor' },
		{ value: '176', label: 'Off Topic' },
		{ value: '138', label: 'Overclock' },
		{ value: '137', label: 'Periféricos' },
		{ value: '79', label: 'Portátiles' },
		{ value: '140', label: 'Programas' },
		{ value: '360', label: 'Ratón' },
		{ value: '80', label: 'Redes' },
		{ value: '363', label: 'Review' },
		{ value: '139', label: 'Soporte Técnico' },
		{ value: '361', label: 'Teclado' },
		{ value: '81', label: 'Windows' },
	],

	// ─── COMUNIDAD ───

	mediavida: [
		{ value: '36', label: 'Bug' },
		{ value: '156', label: 'Debate' },
		{ value: '1', label: 'Noticia' },
		{ value: '14', label: 'Pregunta' },
		{ value: '4', label: 'Queja' },
		{ value: '139', label: 'Soporte Técnico' },
		{ value: '37', label: 'Sugerencia' },
	],
}

/**
 * Get categories for a specific subforum
 */
export function getCategoriesForSubforum(slug: string): SubforumCategory[] {
	return SUBFORUM_CATEGORIES[slug] || []
}

/**
 * Check if a subforum has categories defined
 */
export function hasCategories(slug: string): boolean {
	return slug in SUBFORUM_CATEGORIES && SUBFORUM_CATEGORIES[slug].length > 0
}
