/**
 * Theme Presets - Collection of predefined themes
 */
import type { ThemePreset } from '@/types/theme'

/** * Default Theme - Zinc Crisp / Modern Slate 
 * Optimized for high contrast and visual cleanliness.
 */
export const defaultPreset: ThemePreset = {
  id: 'default',
  name: 'Moderno',
  description: 'Tema por defecto con tonos zinc y slate',
  colors: {
    light: {
      background: '#ffffff',
      foreground: '#09090b',
      card: '#ffffff',
      cardForeground: '#09090b',
      popover: '#ffffff',
      popoverForeground: '#09090b',
      primary: '#18181b',
      primaryForeground: '#fafafa',
      secondary: '#f4f4f5',
      secondaryForeground: '#18181b',
      muted: '#f4f4f5',
      mutedForeground: '#71717a',
      accent: '#f4f4f5',
      accentForeground: '#18181b',
      destructive: '#ef4444',
      destructiveForeground: '#fafafa',
      border: '#e4e4e7',
      input: '#e4e4e7',
      ring: '#18181b',
      sidebar: '#fafafa',
      sidebarForeground: '#18181b',
      sidebarPrimary: '#18181b',
      sidebarPrimaryForeground: '#fafafa',
      sidebarAccent: '#f4f4f5',
      sidebarAccentForeground: '#18181b',
      sidebarBorder: '#e4e4e7',
      sidebarRing: '#18181b',
      chart1: '#71717a',
      chart2: '#27272a',
      chart3: '#52525b',
      chart4: '#a1a1aa',
      chart5: '#d4d4d8',
      tableHeader: '#f4f4f5',
      tableHeaderForeground: '#18181b',
      tableRow: '#ffffff',
      tableRowAlt: '#fafafa',
      tableRowForeground: '#09090b',
      tableBorder: '',
      },
    dark: {
      background: '#09090b',
      foreground: '#fafafa',
      card: '#09090b',
      cardForeground: '#fafafa',
      popover: '#09090b',
      popoverForeground: '#fafafa',
      primary: '#fafafa',
      primaryForeground: '#18181b',
      secondary: '#27272a',
      secondaryForeground: '#fafafa',
      muted: '#27272a',
      mutedForeground: '#a1a1aa',
      accent: '#27272a',
      accentForeground: '#fafafa',
      destructive: '#7f1d1d',
      destructiveForeground: '#fafafa',
      border: '#27272a',
      input: '#27272a',
      ring: '#d4d4d8',
      sidebar: '#09090b',
      sidebarForeground: '#fafafa',
      sidebarPrimary: '#fafafa',
      sidebarPrimaryForeground: '#18181b',
      sidebarAccent: '#27272a',
      sidebarAccentForeground: '#fafafa',
      sidebarBorder: '#27272a',
      sidebarRing: '#d4d4d8',
      chart1: '#a1a1aa',
      chart2: '#fafafa',
      chart3: '#d4d4d8',
      chart4: '#52525b',
      chart5: '#27272a',
      tableHeader: '#27272a',
      tableHeaderForeground: '#fafafa',
      tableRow: '#09090b',
      tableRowAlt: '#18181b',
      tableRowForeground: '#fafafa',
      tableBorder: '',
      },
  },
  radius: '0.625rem',
}

/** * Mediavida Theme - Native forum colors 
 * (INTACTO)
 */
export const mediaviaPreset: ThemePreset = {
  id: 'mediavida',
  name: 'Mediavida',
  description: 'Colores nativos del foro Mediavida',
  colors: {
    light: {
      background: '#f9fcff',
      foreground: '#1c1f22',
      card: '#ffffff',
      cardForeground: '#1c1f22',
      popover: '#ffffff',
      popoverForeground: '#1c1f22',
      primary: '#1c1f22',
      primaryForeground: '#ffffff',
      secondary: '#ecedef',
      secondaryForeground: '#1c1f22',
      muted: '#ecedef',
      mutedForeground: '#7c888d',
      accent: '#ecedef',
      accentForeground: '#1c1f22',
      destructive: '#ef262d',
      destructiveForeground: '#ffffff',
      border: '#d3dce4',
      input: '#d3dce4',
      ring: '#1c1f22',
      sidebar: '#ffffff',
      sidebarForeground: '#1c1f22',
      sidebarPrimary: '#1c1f22',
      sidebarPrimaryForeground: '#ffffff',
      sidebarAccent: '#ecedef',
      sidebarAccentForeground: '#1c1f22',
      sidebarBorder: '#d3dce4',
      sidebarRing: '#1c1f22',
      chart1: '#fc8f22',
      chart2: '#5ca5ee',
      chart3: '#11a222',
      chart4: '#e02f2f',
      chart5: '#9333ea',
      tableHeader: '#ecedef',
      tableHeaderForeground: '#1c1f22',
      tableRow: '#f9fcff',
      tableRowAlt: '#f2f5f7',
      tableRowForeground: '#1c1f22',
      tableBorder: '',
      },
    dark: {
      background: '#101213',
      foreground: '#e7e9ea',
      card: '#1c1f22',
      cardForeground: '#e7e9ea',
      popover: '#1c1f22',
      popoverForeground: '#e7e9ea',
      primary: '#fc8f22',
      primaryForeground: '#0f1419',
      secondary: '#232a2e',
      secondaryForeground: '#e7e9ea',
      muted: '#2f383e',
      mutedForeground: '#A5AEB5',
      accent: '#232a2e',
      accentForeground: '#fc8f22',
      destructive: '#e02f2f',
      destructiveForeground: '#ffffff',
      border: '#30353a',
      input: '#30353a',
      ring: '#fc8f22',
      sidebar: '#1c1f22',
      sidebarForeground: '#e7e9ea',
      sidebarPrimary: '#fc8f22',
      sidebarPrimaryForeground: '#0f1419',
      sidebarAccent: '#232a2e',
      sidebarAccentForeground: '#e7e9ea',
      sidebarBorder: '#384045',
      sidebarRing: '#fc8f22',
      chart1: '#fc8f22',
      chart2: '#5ca5ee',
      chart3: '#11a222',
      chart4: '#e02f2f',
      chart5: '#a855f7',
      tableHeader: '#272d30',
      tableHeaderForeground: '#e7e9ea',
      tableRow: '#39464c',
      tableRowAlt: '#445259',
      tableRowForeground: '#e7e9ea',
      tableBorder: '',
      },
  },
  radius: '0.5rem',
}

/** * Ocean Theme - Deep blues
 * WCAG Fix: Primary Light darkened for contrast with white text.
 */
export const oceanPreset: ThemePreset = {
  id: 'ocean',
  name: 'Océano',
  description: 'Azules profundos inspirados en el mar',
  colors: {
    light: {
      background: '#f0f9ff',
      foreground: '#0c4a6e',
      card: '#ffffff',
      cardForeground: '#0c4a6e',
      popover: '#ffffff',
      popoverForeground: '#0c4a6e',
      primary: '#0284c7', // Sky 600 - Good contrast
      primaryForeground: '#ffffff',
      secondary: '#e0f2fe',
      secondaryForeground: '#0c4a6e',
      muted: '#e0f2fe',
      mutedForeground: '#475569',
      accent: '#bae6fd',
      accentForeground: '#026aa7',
      destructive: '#dc2626',
      destructiveForeground: '#ffffff',
      border: '#bae6fd',
      input: '#bae6fd',
      ring: '#0284c7',
      sidebar: '#e0f2fe',
      sidebarForeground: '#0c4a6e',
      sidebarPrimary: '#0284c7',
      sidebarPrimaryForeground: '#ffffff',
      sidebarAccent: '#bae6fd',
      sidebarAccentForeground: '#0c4a6e',
      sidebarBorder: '#bae6fd',
      sidebarRing: '#0284c7',
      chart1: '#0284c7',
      chart2: '#0891b2',
      chart3: '#06b6d4',
      chart4: '#14b8a6',
      chart5: '#0d9488',
      tableHeader: '#e0f2fe',
      tableHeaderForeground: '#0c4a6e',
      tableRow: '#f0f9ff',
      tableRowAlt: '#e0f2fe',
      tableRowForeground: '#0c4a6e',
      tableBorder: '',
      },
    dark: {
      background: '#0b1120', // Very dark blue (almost black)
      foreground: '#e0f2fe',
      card: '#111a2c', // Slightly lighter for cards
      cardForeground: '#e0f2fe',
      popover: '#111a2c',
      popoverForeground: '#e0f2fe',
      primary: '#38bdf8', // Sky 400
      primaryForeground: '#0b1120',
      secondary: '#1e293b',
      secondaryForeground: '#e0f2fe',
      muted: '#1e293b',
      mutedForeground: '#94a3b8',
      accent: '#1e293b',
      accentForeground: '#38bdf8',
      destructive: '#ef4444',
      destructiveForeground: '#0b1120',
      border: '#1e293b',
      input: '#1e293b',
      ring: '#38bdf8',
      sidebar: '#0f172a',
      sidebarForeground: '#e0f2fe',
      sidebarPrimary: '#38bdf8',
      sidebarPrimaryForeground: '#0b1120',
      sidebarAccent: '#1e293b',
      sidebarAccentForeground: '#e0f2fe',
      sidebarBorder: '#1e293b',
      sidebarRing: '#38bdf8',
      chart1: '#38bdf8',
      chart2: '#22d3ee',
      chart3: '#2dd4bf',
      chart4: '#34d399',
      chart5: '#4ade80',
      tableHeader: '#111a2c',
      tableHeaderForeground: '#e0f2fe',
      tableRow: '#0b1120',
      tableRowAlt: '#111a2c',
      tableRowForeground: '#e0f2fe',
      tableBorder: '',
      },
  },
  radius: '0.75rem',
}

/** * Forest Theme - Natural greens
 * WCAG Fix: Primary Light changed to Green 700 to pass contrast ratio.
 */
export const forestPreset: ThemePreset = {
  id: 'forest',
  name: 'Bosque',
  description: 'Verdes naturales y terrosos',
  colors: {
    light: {
      background: '#f8fafc', // Cold off-white
      foreground: '#14532d', // Green 950
      card: '#ffffff',
      cardForeground: '#14532d',
      popover: '#ffffff',
      popoverForeground: '#14532d',
      primary: '#15803d', // Green 700 (Darker to allow white text)
      primaryForeground: '#ffffff',
      secondary: '#dcfce7',
      secondaryForeground: '#14532d',
      muted: '#f0fdf4',
      mutedForeground: '#65a30d',
      accent: '#dcfce7',
      accentForeground: '#14532d',
      destructive: '#dc2626',
      destructiveForeground: '#ffffff',
      border: '#cbd5e1', // Soft slate for structure
      input: '#cbd5e1',
      ring: '#15803d',
      sidebar: '#f0fdf4',
      sidebarForeground: '#14532d',
      sidebarPrimary: '#15803d',
      sidebarPrimaryForeground: '#ffffff',
      sidebarAccent: '#dcfce7',
      sidebarAccentForeground: '#14532d',
      sidebarBorder: '#bbf7d0',
      sidebarRing: '#15803d',
      chart1: '#15803d',
      chart2: '#22c55e',
      chart3: '#84cc16',
      chart4: '#a3e635',
      chart5: '#65a30d',
      tableHeader: '#f0fdf4',
      tableHeaderForeground: '#14532d',
      tableRow: '#ffffff',
      tableRowAlt: '#f0fdf4',
      tableRowForeground: '#14532d',
      tableBorder: '',
      },
    dark: {
      background: '#022c22', // Deep Green 950
      foreground: '#ecfccb', // Lime 100
      card: '#064e3b', // Green 900
      cardForeground: '#ecfccb',
      popover: '#064e3b',
      popoverForeground: '#ecfccb',
      primary: '#4ade80', // Green 400
      primaryForeground: '#022c22',
      secondary: '#14532d',
      secondaryForeground: '#ecfccb',
      muted: '#14532d',
      mutedForeground: '#86efac',
      accent: '#14532d',
      accentForeground: '#4ade80',
      destructive: '#f87171',
      destructiveForeground: '#022c22',
      border: '#14532d',
      input: '#14532d',
      ring: '#4ade80',
      sidebar: '#022c22',
      sidebarForeground: '#ecfccb',
      sidebarPrimary: '#4ade80',
      sidebarPrimaryForeground: '#022c22',
      sidebarAccent: '#064e3b',
      sidebarAccentForeground: '#ecfccb',
      sidebarBorder: '#14532d',
      sidebarRing: '#4ade80',
      chart1: '#4ade80',
      chart2: '#34d399',
      chart3: '#a3e635',
      chart4: '#bef264',
      chart5: '#86efac',
      tableHeader: '#064e3b',
      tableHeaderForeground: '#ecfccb',
      tableRow: '#022c22',
      tableRowAlt: '#064e3b',
      tableRowForeground: '#ecfccb',
      tableBorder: '',
      },
  },
  radius: '0.5rem',
}

/** * Sunset Theme - Warm oranges and reds
 * WCAG Fix: Critical Primary Light. Orange on white needs to be dark (#c2410c)
 */
export const sunsetPreset: ThemePreset = {
  id: 'sunset',
  name: 'Atardecer',
  description: 'Colores cálidos de atardecer',
  colors: {
    light: {
      background: '#fff7ed', // Orange 50
      foreground: '#431407', // Orange 950
      card: '#ffffff',
      cardForeground: '#431407',
      popover: '#ffffff',
      popoverForeground: '#431407',
      primary: '#c2410c', // Orange 700 (Crucial for WCAG on white)
      primaryForeground: '#ffffff',
      secondary: '#ffedd5',
      secondaryForeground: '#431407',
      muted: '#ffedd5',
      mutedForeground: '#9a3412',
      accent: '#ffedd5',
      accentForeground: '#c2410c',
      destructive: '#b91c1c',
      destructiveForeground: '#ffffff',
      border: '#fed7aa',
      input: '#fed7aa',
      ring: '#ea580c',
      sidebar: '#fff7ed',
      sidebarForeground: '#431407',
      sidebarPrimary: '#c2410c',
      sidebarPrimaryForeground: '#ffffff',
      sidebarAccent: '#ffedd5',
      sidebarAccentForeground: '#431407',
      sidebarBorder: '#fed7aa',
      sidebarRing: '#ea580c',
      chart1: '#ea580c',
      chart2: '#f97316',
      chart3: '#fb923c',
      chart4: '#ef4444',
      chart5: '#dc2626',
      tableHeader: '#ffedd5',
      tableHeaderForeground: '#431407',
      tableRow: '#fff7ed',
      tableRowAlt: '#ffedd5',
      tableRowForeground: '#431407',
      tableBorder: '',
      },
    dark: {
      background: '#0f0a0a', // Casi negro rojizo
      foreground: '#fdba74', // Orange 300
      card: '#1c100c',
      cardForeground: '#fdba74',
      popover: '#1c100c',
      popoverForeground: '#fdba74',
      primary: '#fb923c', // Orange 400
      primaryForeground: '#2a1208',
      secondary: '#2a1208',
      secondaryForeground: '#fdba74',
      muted: '#2a1208',
      mutedForeground: '#9a3412',
      accent: '#2a1208',
      accentForeground: '#fb923c',
      destructive: '#7f1d1d',
      destructiveForeground: '#fdba74',
      border: '#431407',
      input: '#431407',
      ring: '#fb923c',
      sidebar: '#0f0a0a',
      sidebarForeground: '#fdba74',
      sidebarPrimary: '#fb923c',
      sidebarPrimaryForeground: '#2a1208',
      sidebarAccent: '#1c100c',
      sidebarAccentForeground: '#fdba74',
      sidebarBorder: '#431407',
      sidebarRing: '#fb923c',
      chart1: '#fb923c',
      chart2: '#f97316',
      chart3: '#fbbf24',
      chart4: '#f87171',
      chart5: '#fb7185',
      tableHeader: '#1c100c',
      tableHeaderForeground: '#fdba74',
      tableRow: '#0f0a0a',
      tableRowAlt: '#1c100c',
      tableRowForeground: '#fdba74',
      tableBorder: '',
      },
  },
  radius: '0.75rem',
}

/** * Rose Pine Theme
 * Faithful to the original theme but with polished borders.
 */
export const rosePinePreset: ThemePreset = {
  id: 'rose-pine',
  name: 'Rose Pine',
  description: 'Inspirado en el tema Rose Pine',
  colors: {
    light: {
      background: '#faf4ed',
      foreground: '#575279',
      card: '#fffaf3',
      cardForeground: '#575279',
      popover: '#fffaf3',
      popoverForeground: '#575279',
      primary: '#d7827e',
      primaryForeground: '#faf4ed',
      secondary: '#f2e9e1',
      secondaryForeground: '#575279',
      muted: '#f2e9e1',
      mutedForeground: '#797593',
      accent: '#f2e9e1',
      accentForeground: '#575279',
      destructive: '#b4637a',
      destructiveForeground: '#faf4ed',
      border: '#dfdad9', // Surface
      input: '#dfdad9',
      ring: '#d7827e',
      sidebar: '#faf4ed',
      sidebarForeground: '#575279',
      sidebarPrimary: '#d7827e',
      sidebarPrimaryForeground: '#faf4ed',
      sidebarAccent: '#f2e9e1',
      sidebarAccentForeground: '#575279',
      sidebarBorder: '#dfdad9',
      sidebarRing: '#d7827e',
      chart1: '#d7827e',
      chart2: '#ea9d34',
      chart3: '#56949f',
      chart4: '#286983',
      chart5: '#907aa9',
      tableHeader: '#f2e9e1',
      tableHeaderForeground: '#575279',
      tableRow: '#faf4ed',
      tableRowAlt: '#fffaf3',
      tableRowForeground: '#575279',
      tableBorder: '',
      },
    dark: {
      background: '#191724',
      foreground: '#e0def4',
      card: '#1f1d2e',
      cardForeground: '#e0def4',
      popover: '#1f1d2e',
      popoverForeground: '#e0def4',
      primary: '#ebbcba',
      primaryForeground: '#191724',
      secondary: '#26233a',
      secondaryForeground: '#e0def4',
      muted: '#26233a',
      mutedForeground: '#908caa',
      accent: '#26233a',
      accentForeground: '#e0def4',
      destructive: '#eb6f92',
      destructiveForeground: '#191724',
      border: '#26233a', // Highlight low
      input: '#26233a',
      ring: '#ebbcba',
      sidebar: '#191724',
      sidebarForeground: '#e0def4',
      sidebarPrimary: '#ebbcba',
      sidebarPrimaryForeground: '#191724',
      sidebarAccent: '#1f1d2e',
      sidebarAccentForeground: '#e0def4',
      sidebarBorder: '#26233a',
      sidebarRing: '#ebbcba',
      chart1: '#ebbcba',
      chart2: '#f6c177',
      chart3: '#9ccfd8',
      chart4: '#31748f',
      chart5: '#c4a7e7',
      tableHeader: '#1f1d2e',
      tableHeaderForeground: '#e0def4',
      tableRow: '#191724',
      tableRowAlt: '#21202e',
      tableRowForeground: '#e0def4',
      tableBorder: '',
      },
  },
  radius: '0.5rem',
}

/** * Nord Theme
 * Adjusted to maintain coolness without losing contrast.
 */
export const nordPreset: ThemePreset = {
  id: 'nord',
  name: 'Nord',
  description: 'Tema ártico inspirado en Nord',
  colors: {
    light: {
      background: '#eceff4',
      foreground: '#2e3440',
      card: '#ffffff',
      cardForeground: '#2e3440',
      popover: '#ffffff',
      popoverForeground: '#2e3440',
      primary: '#5e81ac', // Nord 10
      primaryForeground: '#eceff4',
      secondary: '#d8dee9',
      secondaryForeground: '#2e3440',
      muted: '#e5e9f0',
      mutedForeground: '#4c566a',
      accent: '#d8dee9',
      accentForeground: '#2e3440',
      destructive: '#bf616a',
      destructiveForeground: '#eceff4',
      border: '#d8dee9',
      input: '#d8dee9',
      ring: '#5e81ac',
      sidebar: '#e5e9f0',
      sidebarForeground: '#2e3440',
      sidebarPrimary: '#5e81ac',
      sidebarPrimaryForeground: '#eceff4',
      sidebarAccent: '#d8dee9',
      sidebarAccentForeground: '#2e3440',
      sidebarBorder: '#d8dee9',
      sidebarRing: '#5e81ac',
      chart1: '#5e81ac',
      chart2: '#81a1c1',
      chart3: '#88c0d0',
      chart4: '#8fbcbb',
      chart5: '#a3be8c',
      tableHeader: '#e5e9f0',
      tableHeaderForeground: '#2e3440',
      tableRow: '#eceff4',
      tableRowAlt: '#e5e9f0',
      tableRowForeground: '#2e3440',
      tableBorder: '',
      },
    dark: {
      background: '#242933', // Custom Nord dark slightly darker
      foreground: '#eceff4',
      card: '#2e3440', // Nord 0
      cardForeground: '#eceff4',
      popover: '#2e3440',
      popoverForeground: '#eceff4',
      primary: '#88c0d0', // Nord 8
      primaryForeground: '#2e3440',
      secondary: '#3b4252',
      secondaryForeground: '#eceff4',
      muted: '#3b4252', // Nord 1
      mutedForeground: '#d8dee9',
      accent: '#434c5e', // Nord 2
      accentForeground: '#eceff4',
      destructive: '#bf616a',
      destructiveForeground: '#eceff4',
      border: '#3b4252',
      input: '#3b4252',
      ring: '#88c0d0',
      sidebar: '#242933',
      sidebarForeground: '#eceff4',
      sidebarPrimary: '#88c0d0',
      sidebarPrimaryForeground: '#2e3440',
      sidebarAccent: '#3b4252',
      sidebarAccentForeground: '#eceff4',
      sidebarBorder: '#3b4252',
      sidebarRing: '#88c0d0',
      chart1: '#88c0d0',
      chart2: '#81a1c1',
      chart3: '#5e81ac',
      chart4: '#8fbcbb',
      chart5: '#a3be8c',
      tableHeader: '#2e3440',
      tableHeaderForeground: '#eceff4',
      tableRow: '#242933',
      tableRowAlt: '#2e3440',
      tableRowForeground: '#eceff4',
      tableBorder: '',
      },
  },
  radius: '0.375rem',
}

/** * Catppuccin Mocha Theme
 * Faithful official colors and high contrast.
 */
export const catppuccinPreset: ThemePreset = {
  id: 'catppuccin',
  name: 'Catppuccin',
  description: 'Tema pastel inspirado en Catppuccin Mocha',
  colors: {
    light: {
      background: '#eff1f5', // Latte Base
      foreground: '#4c4f69', // Latte Text
      card: '#ffffff',
      cardForeground: '#4c4f69',
      popover: '#ffffff',
      popoverForeground: '#4c4f69',
      primary: '#8839ef', // Mauve
      primaryForeground: '#ffffff',
      secondary: '#e6e9ef',
      secondaryForeground: '#4c4f69',
      muted: '#ccd0da',
      mutedForeground: '#6c6f85', // Subtext0
      accent: '#ccd0da',
      accentForeground: '#4c4f69',
      destructive: '#d20f39', // Red
      destructiveForeground: '#ffffff',
      border: '#bcc0cc', // Surface1
      input: '#bcc0cc',
      ring: '#8839ef',
      sidebar: '#e6e9ef',
      sidebarForeground: '#4c4f69',
      sidebarPrimary: '#8839ef',
      sidebarPrimaryForeground: '#ffffff',
      sidebarAccent: '#ccd0da',
      sidebarAccentForeground: '#4c4f69',
      sidebarBorder: '#bcc0cc',
      sidebarRing: '#8839ef',
      chart1: '#8839ef',
      chart2: '#1e66f5',
      chart3: '#179299',
      chart4: '#40a02b',
      chart5: '#df8e1d',
      tableHeader: '#e6e9ef',
      tableHeaderForeground: '#4c4f69',
      tableRow: '#eff1f5',
      tableRowAlt: '#e6e9ef',
      tableRowForeground: '#4c4f69',
      tableBorder: '',
      },
    dark: {
      background: '#1e1e2e', // Mocha Base
      foreground: '#cdd6f4', // Mocha Text
      card: '#181825', // Mocha Mantle (Better for cards)
      cardForeground: '#cdd6f4',
      popover: '#181825',
      popoverForeground: '#cdd6f4',
      primary: '#cba6f7', // Mauve
      primaryForeground: '#1e1e2e',
      secondary: '#313244', // Surface0
      secondaryForeground: '#cdd6f4',
      muted: '#313244',
      mutedForeground: '#a6adc8', // Subtext0
      accent: '#45475a', // Surface1
      accentForeground: '#cdd6f4',
      destructive: '#f38ba8', // Red
      destructiveForeground: '#1e1e2e',
      border: '#45475a', // Surface1
      input: '#45475a',
      ring: '#cba6f7',
      sidebar: '#11111b', // Crust
      sidebarForeground: '#cdd6f4',
      sidebarPrimary: '#cba6f7',
      sidebarPrimaryForeground: '#1e1e2e',
      sidebarAccent: '#313244',
      sidebarAccentForeground: '#cdd6f4',
      sidebarBorder: '#313244',
      sidebarRing: '#cba6f7',
      chart1: '#cba6f7',
      chart2: '#89b4fa',
      chart3: '#94e2d5',
      chart4: '#a6e3a1',
      chart5: '#f9e2af',
      tableHeader: '#181825',
      tableHeaderForeground: '#cdd6f4',
      tableRow: '#1e1e2e',
      tableRowAlt: '#181825',
      tableRowForeground: '#cdd6f4',
      tableBorder: '',
      },
  },
  radius: '0.625rem',
}

/** All available presets */
export const ALL_PRESETS: ThemePreset[] = [
  defaultPreset,
  mediaviaPreset,
  oceanPreset,
  forestPreset,
  sunsetPreset,
  rosePinePreset,
  nordPreset,
  catppuccinPreset,
]

/** Get preset by ID */
export function getPresetById(id: string): ThemePreset | undefined {
  return ALL_PRESETS.find(p => p.id === id)
}